services:
  app:
    build:
      context: .
      target: runner
    image: starter-express-prisma-jwt:prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ${COMPOSE_ENV_FILE:-.env.production}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:?Set POSTGRES_USER}:${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:?Set POSTGRES_DB}?schema=public}
      RATE_LIMIT_REDIS_URL: ${RATE_LIMIT_REDIS_URL:-redis://:${REDIS_PASSWORD:?Set REDIS_PASSWORD for Redis}@redis:6379/0}
      PORT: 3000
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:?Set JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:?Set JWT_REFRESH_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS:?Set CORS_ORIGINS}
      METRICS_ENABLED: ${METRICS_ENABLED:-false}
      METRICS_GUARD: ${METRICS_GUARD:-none}
    ports:
      - "3000:3000"
    healthcheck:
      test:
        - CMD-SHELL
        - >
          node -e "fetch('http://127.0.0.1:3000/ready').then(r => {
            if (r.status === 200) process.exit(0);
            process.exit(1);
          }).catch(() => process.exit(1));"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER for Postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD for Postgres}
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB for Postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"",
        ]
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    image: redis:7.4-alpine
    command:
      - sh
      - -c
      - |
        if [ -z "$${REDIS_PASSWORD}" ]; then
          echo "REDIS_PASSWORD is required" >&2
          exit 1
        fi
        exec redis-server --appendonly yes --requirepass "$${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?Set REDIS_PASSWORD for Redis}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "REDISCLI_AUTH=\"$${REDIS_PASSWORD}\" redis-cli ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 12

volumes:
  postgres_data:
  redis_data:
