apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: starter-api
  namespace: replace-me
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: starter-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
